server:
  port: 8080

spring:
  application:
    name: syzl-cloud-gateway
  cloud:
    gateway:
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: syzl-cloud-system
          uri: lb://syzl-cloud-system
          order: 999999
          predicates:
            - Path=/**
#        - id: syzl-cloud-new
#          uri: lb://syzl-cloud-new
#          order: 1
#          predicates:
#            - Path=/**
#          filters:
#            - StripPrefix=1
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        server-addr: @nacos.server-addr@
        namespace: @nacos.namespace@
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
  config:
    import:
      - optional:nacos:syzl-datasource.yaml
knife4j:
  # 聚合swagger文档
  gateway:
    enabled: true
    # 指定服务发现的模式聚合微服务文档，并且是默认`default`分组
    strategy: discover
    discover:
      enabled: true
      version : openapi3
---
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
